'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabaseClient';
import {SiteHeader,SiteFooter} from '../../components/SiteChrome';
import {formatOrderNumber} from '../../lib/orderNumber';

const shell={maxWidth:1120,margin:'48px auto 86px',padding:'0 24px'};
const grid={display:'grid',gridTemplateColumns:'260px minmax(0,1fr)',gap:34,alignItems:'start'};
const sideCard={background:'#f7f8f4',border:'1px solid #e3e8df',borderRadius:18,padding:'24px 22px',boxShadow:'0 8px 24px rgba(55,70,50,.06)'};
const ordersCard={background:'#fff',border:'1px solid #e7e1dc',borderRadius:18,padding:'28px',boxShadow:'0 8px 28px rgba(55,70,50,.06)',minHeight:260};

export default function Account(){
 const [user,setUser]=useState(null),[orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[messageType,setMessageType]=useState('success'),[mode,setMode]=useState('signin');
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();setUser(user);if(user?.email){const response=await fetch('/api/account/orders',{cache:'no-store'});const payload=await response.json().catch(()=>({orders:[]}));setOrders(response.ok?(payload.orders||[]):[])}setLoading(false)})()},[]);
 async function signIn(e){e.preventDefault();setMessage('');const fd=new FormData(e.currentTarget),email=fd.get('email'),password=fd.get('password');const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setMessageType('error');setMessage(error.message)}else{location.href='/account'}}
 async function createAccount(e){e.preventDefault();setMessage('');const fd=new FormData(e.currentTarget),email=fd.get('email'),password=fd.get('password');const {error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/account'}});if(error){setMessageType('error');setMessage(error.message)}else{setMessageType('success');setMessage('Account created. If confirmation is required, please check your email. Otherwise you can sign in now.')}}
 async function forgotPassword(){const email=document.querySelector('input[name="email"]')?.value;if(!email){setMessageType('error');setMessage('Enter your email address first.');return}const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/account/reset-password'});setMessageType(error?'error':'success');setMessage(error?error.message:'Password reset email sent.')}

 if(loading)return <><SiteHeader/><main className="account-page"><p>Loading…</p></main><SiteFooter/></>;
 if(!user)return <><SiteHeader/><main className="account-login"><h1>Your account</h1><p>{mode==='signin'?'Sign in to see your orders and buy again.':'Create an account to keep your order history in one place.'}</p><form onSubmit={mode==='signin'?signIn:createAccount}><input name="email" type="email" placeholder="Email address" required/><input name="password" type="password" placeholder="Password" minLength="6" required/><label style={{display:'flex',alignItems:'center',gap:8,fontSize:14,margin:'4px 0 12px'}}><input type="checkbox" defaultChecked style={{width:'auto'}}/> Stay signed in</label><button className="btn">{mode==='signin'?'Sign in':'Create account'}</button>{mode==='signin'&&<button type="button" onClick={forgotPassword} style={{border:0,background:'none',padding:'12px 0 0',cursor:'pointer',textDecoration:'underline'}}>Forgot password?</button>}{message&&<p role="status" className={messageType==='error'?'checkout-error':'account-message'}>{message}</p>}</form><p style={{marginTop:18}}>{mode==='signin'?'New customer? ':'Already have an account? '}<button type="button" onClick={()=>{setMode(mode==='signin'?'signup':'signin');setMessage('')}} style={{border:0,background:'none',padding:0,cursor:'pointer',textDecoration:'underline'}}>{mode==='signin'?'Create an account':'Sign in'}</button></p></main><SiteFooter/></>;
 const firstName=user.user_metadata?.first_name;
 return <><SiteHeader/><main style={shell}><div className="account-polish-grid" style={grid}><aside style={sideCard}><div style={{fontSize:12,textTransform:'uppercase',letterSpacing:'.12em',color:'#7f9777',fontWeight:600,marginBottom:8}}>My account</div><h1 style={{fontFamily:"'Playfair Display',serif",fontWeight:400,fontSize:30,lineHeight:1.2,margin:'0 0 8px',color:'#2a2a2a'}}>{firstName?`Hi, ${firstName}`:'Your account'}</h1><p style={{margin:'0 0 24px',color:'#656b63',overflowWrap:'anywhere'}}>{user.email}</p><nav style={{display:'grid',gap:9}}><div style={{background:'#eef3ec',borderRadius:10,padding:'11px 13px',fontWeight:600,color:'#2f3a2f'}}>Orders</div><Link href="/account/profile" style={{padding:'11px 13px',borderRadius:10,color:'#656b63'}}>Profile</Link></nav></aside><section style={ordersCard}><div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',gap:20,marginBottom:22}}><div><div style={{fontSize:12,textTransform:'uppercase',letterSpacing:'.12em',color:'#7f9777',fontWeight:600,marginBottom:6}}>Order history</div><h2 style={{fontFamily:"'Playfair Display',serif",fontWeight:400,fontSize:34,margin:0}}>Your orders</h2></div>{orders.length>0&&<span style={{color:'#777',fontSize:14}}>{orders.length} {orders.length===1?'order':'orders'}</span>}</div>{!orders.length?<div style={{border:'1px dashed #d8ded4',background:'#fafbf8',borderRadius:14,padding:'32px 24px',textAlign:'center'}}><div style={{fontSize:30,marginBottom:8}}>♡</div><strong style={{display:'block',fontSize:18,marginBottom:6}}>No orders yet</strong><p style={{margin:'0 0 18px',color:'#656b63'}}>When you place an order, you’ll be able to track it here and buy it again easily.</p><Link href="/collections/all" className="btn">Start shopping</Link></div>:orders.map(o=>{const item=o.order_items?.[0];const label=o.fulfilment_status==='fulfilled'?(o.shipping_method==='collection'?'Collected':'Dispatched'):o.status==='paid'?'Order received':o.fulfilment_status==='ready'&&o.shipping_method==='collection'?'Ready for collection':o.fulfilment_status||'Processing';return <article className="order-card" key={o.id}><div><span style={{display:'inline-block',fontSize:12,fontWeight:600,color:'#52644d',background:'#eef3ec',borderRadius:999,padding:'5px 9px',marginBottom:8}}>{label}</span><p style={{margin:'0 0 4px',fontWeight:600}}>Order #{formatOrderNumber(o.order_number)}</p><p style={{margin:'0 0 4px',color:'#656b63'}}>£{(o.total_pence/100).toFixed(2)} GBP</p>{item&&<small style={{color:'#777'}}>{item.product_title}</small>}</div>{item&&<Link className="buy-again" href={'/product/'+item.product_slug}>Buy again</Link>}</article>})}</section></div><style jsx>{`@media(max-width:760px){.account-polish-grid{grid-template-columns:1fr!important}.account-polish-grid section{padding:22px!important}}`}</style></main><SiteFooter/></>;
}
