'use client';
import {useState} from 'react';
import Link from 'next/link';
import {money,products} from '../../../lib/products';
import {commerce,ensureCart,supabase} from '../../../lib/supabaseClient';
import {SiteHeader,SiteFooter} from '../../../components/SiteChrome';
const maxDesignsFor=(p,index)=>p.slug==='a4-edible-print-sheet'?[1,4,10][index]:[1,4,10,30][index];
export default function ProductClient({p}){
 const [variant,setVariant]=useState(0),[qty,setQty]=useState(1),[files,setFiles]=useState([]),[main,setMain]=useState(p.image),[added,setAdded]=useState(false),[busy,setBusy]=useState(false);
 async function add(){if(busy)return;const selected=[...files],max=maxDesignsFor(p,variant);if(!selected.length)return alert('Please upload your image(s) before adding to basket.');if(selected.length>max)return alert(`This option allows up to ${max} design${max===1?'':'s'}.`);for(const f of selected){if(!['image/png','image/jpeg','application/pdf'].includes(f.type))return alert('Artwork must be PNG, JPG or PDF.');if(f.size>20*1024*1024)return alert(`${f.name} is larger than 20MB.`)}setBusy(true);setAdded(false);let auth,itemId;try{auth=await ensureCart();const prepared=await commerce('add_item',{cartId:auth.id,accessToken:auth.token,slug:p.slug,variant,qty,files:selected.map(f=>({name:f.name,size:f.size,type:f.type}))});itemId=prepared.itemId;const ids=[];for(let i=0;i<prepared.uploads.length;i++){const u=prepared.uploads[i],f=selected[i];const {error}=await supabase.storage.from('artwork').uploadToSignedUrl(u.path,u.token,f,{contentType:f.type});if(error)throw error;ids.push(u.artworkId)}await commerce('confirm_uploads',{cartId:auth.id,accessToken:auth.token,artworkIds:ids});setAdded(true)}catch(e){if(auth&&itemId){try{await commerce('remove_item',{cartId:auth.id,accessToken:auth.token,itemId})}catch{}}alert(e.message||'Could not add this item. Please try again.')}finally{setBusy(false)}}
 const related=products.filter(x=>x.slug!==p.slug);
 return <><SiteHeader/><main className="product"><div><img className="producthero" src={main} alt={p.title}/><div className="thumbs">{p.images.map(x=><button key={x} onClick={()=>setMain(x)} aria-label="View product image"><img src={x} alt=""/></button>)}</div></div><div><h1>{p.title}</h1><p className="product-price">{money(p.variants[variant][1])}</p><p className="product-extra">{p.extra}</p><h3>Design</h3><div className="choices">{p.variants.map((v,i)=><button className={variant===i?'selected':''} onClick={()=>setVariant(i)} key={v[0]}><span>{v[0]}</span><strong>{money(v[1])}</strong></button>)}</div><label className="field">Upload your image(s)<input type="file" multiple accept="image/jpeg,image/png,.pdf" onChange={e=>setFiles(e.target.files)}/><small>PNG, JPG or PDF • Maximum 20MB per file • Up to {maxDesignsFor(p,variant)} design{maxDesignsFor(p,variant)===1?'':'s'} for this option.</small></label><label className="field">Quantity<input type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,+e.target.value))}/></label><button className="btn wide" onClick={add} disabled={busy}>{busy?'Uploading artwork…':`Add to basket • ${money(p.variants[variant][1]*qty)}`}</button>{added&&<p className="added">✓ Added securely. <Link href="/cart">View basket</Link></p>}<div className="productinfo" dangerouslySetInnerHTML={{__html:p.descriptionHtml}}/></div></main><section className="recommendations"><h2>You may also like</h2><div className="product-grid">{related.map(x=><article className="product-card" key={x.slug}><Link href={'/product/'+x.slug}><img src={x.image} alt={x.title}/><h3>{x.title}</h3><p>{money(x.variants[0][1])}</p></Link></article>)}</div></section><SiteFooter/></>}
